### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by charliecharlieO-o** [Esquizoo/login_system#3]
complete -> completely

https://github.com/creeper4004/atm_and_login_system/blob/d2dd59135a7c29bdc38101ccccb7144e054a51b0/main.py#L58

`"Who much money do you want to deposit: "` -> `"How much money do you want to deposit:"`
https://github.com/creeper4004/atm_and_login_system/blob/d2dd59135a7c29bdc38101ccccb7144e054a51b0/atm.py#L38

`"How much money do you want to get"` -> `"How much money do you wish to withdraw?:"`
https://github.com/creeper4004/atm_and_login_system/blob/d2dd59135a7c29bdc38101ccccb7144e054a51b0/atm.py#L67

**Comment by creeper4004** [comment]
grammatical problems have already been resolved
